### ISSUE TITLE
Use in fullsize dialog

### ISSUE THREAD

**Issue by tanmuhittin** [zeknoss/vue-magnifier#1]
I use magnifier in a full size dialog of vuetify https://vuetifyjs.com/en/components/dialogs#example-fullscreen . if the page is a long one where it has vertical scroll but currently fullsize dialog is open, vue magnifier behaves in a way that zoom element displays in the bottom of the page where it cannot be displayed

**Comment by zeknoss** [comment]
Hello Muhittin,
Can you provide a sandbox environment (eg codesandbox.io) so we can reproduce the issue and provide a healthy solution.

 Balıkesir'den selamlar!
