### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by tchret** [zeknoss/vue-magnifier#2]
Component doesn't seem to work anymore. 
`vue 2.6.11`

**Comment by zeknoss** [comment]
> Component doesn't seem to work anymore.
> `vue 2.6.11`

Let me take a look and get back to you

**Comment by tchret** [comment]
@zeknoss any update on this?

**Comment by zeknoss** [comment]
> @zeknoss any update on this?

:) it's been a hectic three months my friend, I promise I'll solve this this week!

**Comment by zeknoss** [comment]
:) Hi, I know it's too late but you can check @tchret if you are still in need.
