### ISSUE TITLE
Page scroll issue

### ISSUE THREAD

**Issue by tomcata12** [zeknoss/vue-magnifier#3]
Hello,
This component looks great but when I scroll the page (on the demo) in Chrome the magnifier gets rendered in the wrong place on the image. Is this something that you're aware of or possible to fix?

Many thanks,
Matt

**Comment by zeknoss** [comment]
> Hello,
> This component looks great but when I scroll the page (on the demo) in Chrome the magnifier gets rendered in the wrong place on the image. Is this something that you're aware of or possible to fix?
> 
> Many thanks,
> Matt

Hi Matt,
It seems like you have found a bug. Currently I don't have the time to deal with it right now as my hands are full but any help from you or someone else is more than welcome.

Kind regards,
Burak

**Comment by Sunhat** [comment]
@tomcata12 did you manage to find a solution?

@zeknoss this is the only package I can find that does exactly what I'm looking for, but I don't know where to start in fixing this critical bug. I understand you're busy, but help would be greatly appreciated - Thanks!

**Comment by zeknoss** [comment]
> @tomcata12 did you manage to find a solution?
> 
> @zeknoss this is the only package I can find that does exactly what I'm looking for, but I don't know where to start in fixing this critical bug. I understand you're busy, but help would be greatly appreciated - Thanks!

Hello @tomcata12,
I've fixed the project within a very short time and couldn't find enough time to test it thoroughly. Could you be so kind to clone and test it again and let me know of the results?

Thank you for the support!

**Comment by Sunhat** [comment]
You should definitely publish this on npm - it's a great tool!

**Comment by zeknoss** [comment]
@Sunhat thank you very much. I will in a very short time, hopefully :) Have a great day!
